#! /bin/sh

#env > /etc/envvars
env  | sed -e 's/=/="/' | sed -e 's/$/"/'^C > /etc/envvars

echo "Starting pre-service scripts in /etc/runit_init.d"
for script in /etc/runit_init.d/*
do
    if [ -x "$script" ]; then
        echo >&2 "*** Running: $script"
        $script
        retval=$?
        if [ $retval != 0 ];
        then
            echo >&2 "*** Failed with return value: $?"
            exit $retval
        fi
    fi
done
if [ $# -eq 0 ]; then
    exec /sbin/runsvdir -P /etc/service
fi
/sbin/runsvdir -P /etc/service &

[ "$1" == '--' ] && shift
exec $@

    
